version: 0.1

phases:
  build:
    commands:

      -echo Nothig to do yet
artifacts :
  files :
    - index.html
    - favicon.ico
    - Portfolio-Resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
